// Commit 55: Zauberseite, Zauberwerte und Excel-Zauberdatenbank
(() => {
  "use strict";
  const page=document.getElementById("zauber"), btn=document.getElementById("btnZauber"), root=document.getElementById("zauberInhalt55");
  if(!page||!btn||!root) return;
  const EINHEIT_KEY="pf-reichweiten-einheit";
  const ZAUBERKLASSEN=new Set(["Alchemist","Antipaladin","Arkanist","Barde","Blutwüter","Druide","Ermittler","Hexe","Hexenmeister","Inquisitor","Jäger","Kampfmagus","Kleriker","Kriegspriester","Magier","Mystiker","Paladin","Paktmagier","Schamane","Skalde","Waldläufer"]);
  const STANDARD={Alchemist:["IN","vorbereitet"],Antipaladin:["CH","vorbereitet"],Arkanist:["IN","vorbereitet"],Barde:["CH","spontan"],Blutwüter:["CH","spontan"],Druide:["WE","vorbereitet"],Ermittler:["IN","vorbereitet"],Hexe:["IN","vorbereitet"],Hexenmeister:["CH","spontan"],Inquisitor:["WE","spontan"],Jäger:["WE","spontan"],Kampfmagus:["IN","vorbereitet"],Kleriker:["WE","vorbereitet"],Kriegspriester:["WE","vorbereitet"],Magier:["IN","vorbereitet"],Mystiker:["CH","spontan"],Paladin:["CH","vorbereitet"],Paktmagier:["CH","spontan"],Schamane:["WE","vorbereitet"],Skalde:["CH","spontan"],Waldläufer:["WE","vorbereitet"]};
  let daten=null, klasseAktiv="", suche="", grad="alle";
  const esc=s=>String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
  const ch=()=>typeof aktiverCharakter==="function"?aktiverCharakter():null;
  function zauberKlassen(c){return (c?.klassen||[]).filter(k=>ZAUBERKLASSEN.has(k.name));}
  function config(c,name){c.zauberklassen=c.zauberklassen&&typeof c.zauberklassen==="object"?c.zauberklassen:{};const d=STANDARD[name]||["IN","vorbereitet"];return c.zauberklassen[name]||(c.zauberklassen[name]={attribut:d[0],art:d[1],zs:Number((c.klassen||[]).find(k=>k.name===name)?.stufe||0),konzBonus:0,zrBonus:0,sgBonus:0});}
  function save(){if(typeof speichereCharaktere==="function")speichereCharaktere();}
  function mod(c,key){return typeof attributModifikator==="function"?Number(attributModifikator(c,key)||0):0;}
  function fmt(n){return n>0?`+${n}`:String(n)}
  function einheit(){return localStorage.getItem(EINHEIT_KEY)||"m"}
  function runde(n){n=Math.round(n*100)/100;return Number.isInteger(n)?String(n):String(n).replace(".",",")}
  function reichweiteMeter(text,zs){let t=String(text||"").replace(/,/g,".");if(!t)return null;if(/berührung|du|persönlich|unbegrenzt/i.test(t))return null;let m=t.match(/(\d+(?:\.\d+)?)m(?:\+(\d+(?:\.\d+)?)m\/(\d*)St)?/i);if(!m)return null;let wert=Number(m[1]);if(m[2])wert+=Number(m[2])*Math.floor(zs/Math.max(1,Number(m[3]||1)));return wert;}
  function reichweiteText(text,zs){const m=reichweiteMeter(text,zs);if(m===null)return text||"–";const e=einheit();if(e==="ft")return `${runde(m/0.3)} ft`;if(e==="feld")return `${runde(m/1.5)} Felder`;return `${runde(m)} m`;}
  async function load(){if(daten)return;try{const r=await fetch("data/zauber.json?v=55");if(!r.ok)throw new Error();daten=await r.json()}catch{daten={zauber:[]}}}
  function renderKlassen(c,klassen){const box=document.createElement("section");box.className="zauber-karte-55";box.innerHTML='<h3>Zauberwirker-Einstellungen</h3><div class="zauber-hinweis-55">Die Werte werden pro Charakter und Klasse gespeichert. ZS ist frei anpassbar.</div>';for(const k of klassen){const x=config(c,k.name), row=document.createElement("div");row.className="zauber-klassenzeile-55";row.innerHTML=`<span>${esc(k.name)} ${Number(k.stufe||0)}</span><label>Attribut <select data-a>${["ST","GE","KO","IN","WE","CH"].map(a=>`<option ${a===x.attribut?"selected":""}>${a}</option>`).join("")}</select></label><label>Art <select data-art><option value="vorbereitet" ${x.art==="vorbereitet"?"selected":""}>vorbereitet</option><option value="spontan" ${x.art==="spontan"?"selected":""}>spontan</option></select></label><label>ZS <input data-zs type="number" min="0" max="99" value="${Number(x.zs||0)}"></label>`;row.querySelector('[data-a]').onchange=e=>{x.attribut=e.target.value;save();render()};row.querySelector('[data-art]').onchange=e=>{x.art=e.target.value;save()};row.querySelector('[data-zs]').onchange=e=>{x.zs=Math.max(0,Number(e.target.value)||0);save();render()};box.append(row)}root.append(box)}
  function renderWerte(c,k,x){const am=mod(c,x.attribut), konz=Number(x.zs||0)+am+Number(x.konzBonus||0), zr=Number(x.zs||0)+Number(x.zrBonus||0);const box=document.createElement("section");box.className="zauber-karte-55";box.innerHTML=`<div class="zauber-kopf-55"><h3>${esc(k.name)} ${Number(k.stufe||0)} · ZS ${Number(x.zs||0)} · ${x.attribut} ${fmt(am)}</h3><label>Reichweite <select id="zauberEinheit55"><option value="m">Meter</option><option value="feld">Felder</option><option value="ft">Feet</option></select></label></div><div class="zauber-werte-55"><div class="zauber-wert-55">Konzentration<strong>${fmt(konz)}</strong></div><div class="zauber-wert-55">ZR überwinden<strong>${fmt(zr)}</strong></div><div class="zauber-wert-55">Defensiv Grad 3<strong>SG 21 · W20 ${Math.max(1,21-konz)}+</strong></div></div><div class="zauber-sg-grid-55">${Array.from({length:10},(_,g)=>`<div class="zauber-sg-55">Grad ${g}<br><strong>SG ${10+g+am+Number(x.sgBonus||0)}</strong></div>`).join("")}</div>`;root.append(box);const sel=box.querySelector('#zauberEinheit55');sel.value=einheit();sel.onchange=()=>{localStorage.setItem(EINHEIT_KEY,sel.value);render()}}
  function renderListe(c,k,x){const box=document.createElement("section");box.className="zauber-karte-55";box.innerHTML=`<div class="zauber-filter-55"><input id="zauberSuche55" placeholder="Zauber suchen…" value="${esc(suche)}"><select id="zauberGrad55"><option value="alle">Alle Grade</option>${Array.from({length:10},(_,g)=>`<option value="${g}" ${String(g)===grad?"selected":""}>Grad ${g}</option>`).join("")}</select></div><div id="zauberListe55" class="zauber-liste-55"></div>`;root.append(box);box.querySelector('#zauberSuche55').oninput=e=>{suche=e.target.value;renderZauber(box.querySelector('#zauberListe55'),k,x)};box.querySelector('#zauberGrad55').onchange=e=>{grad=e.target.value;renderZauber(box.querySelector('#zauberListe55'),k,x)};renderZauber(box.querySelector('#zauberListe55'),k,x)}
  function renderZauber(el,k,x){const q=suche.trim().toLocaleLowerCase('de');let list=(daten?.zauber||[]).filter(z=>Object.prototype.hasOwnProperty.call(z.klassen||{},k.name)).filter(z=>grad==='alle'||String(z.klassen[k.name])===grad).filter(z=>!q||z.name.toLocaleLowerCase('de').includes(q));list.sort((a,b)=>(a.klassen[k.name]-b.klassen[k.name])||a.name.localeCompare(b.name,'de'));list=list.slice(0,250);if(!list.length){el.innerHTML='<p class="zauber-leer-55">Keine passenden Zauber gefunden.</p>';return}el.innerHTML=list.map(z=>{const g=z.klassen[k.name], sg=10+Number(g)+mod(ch(),x.attribut)+Number(x.sgBonus||0);return `<article class="zauber-eintrag-55"><div class="zauber-eintrag-kopf-55"><h4>${esc(z.name)} <small>Grad ${g}</small></h4><strong>SG ${sg}</strong></div><div class="zauber-meta-55">${esc(z.schule||'')} · ${esc(z.quelle||'')} · ZR-Wurf W20 ${fmt(Number(x.zs||0)+Number(x.zrBonus||0))}</div><div class="zauber-meta-55">Reichweite: <span class="zauber-reichweite-55">${esc(reichweiteText(z.reichweite,x.zs))}</span>${z.dauer?` · Dauer: ${esc(z.dauer)}`:''}${z.rettungswurf?` · RW: ${esc(z.rettungswurf)}`:''}</div>${z.beschreibung?`<div class="zauber-beschreibung-55">${esc(z.beschreibung)}</div>`:''}</article>`}).join('')}
  async function render(){await load();root.innerHTML='';const c=ch();if(!c){root.innerHTML='<section class="zauber-karte-55 zauber-leer-55">Kein aktiver Charakter.</section>';return}const klassen=zauberKlassen(c);if(!klassen.length){root.innerHTML='<section class="zauber-karte-55 zauber-leer-55">Der aktive Charakter besitzt aktuell keine unterstützte Zauberklasse.</section>';return}if(!klassen.some(k=>k.name===klasseAktiv))klasseAktiv=klassen[0].name;const top=document.createElement('section');top.className='zauber-karte-55';top.innerHTML=`<div class="zauber-kopf-55"><strong>Zauberklasse</strong><select id="zauberKlasse55">${klassen.map(k=>`<option ${k.name===klasseAktiv?'selected':''}>${esc(k.name)}</option>`).join('')}</select></div>`;root.append(top);top.querySelector('select').onchange=e=>{klasseAktiv=e.target.value;render()};renderKlassen(c,klassen);const k=klassen.find(k=>k.name===klasseAktiv),x=config(c,k.name);renderWerte(c,k,x);renderListe(c,k,x)}
  const oldShow=zeigeSeite;zeigeSeite=function(name){oldShow(name);if(name==='zauber')render()};btn.onclick=()=>zeigeSeite('zauber');
  if(typeof waehleCharakter==='function'){const old=waehleCharakter;waehleCharakter=function(id){const r=old(id);if(r&&page.style.display!=='none')render();return r}}
  window.pfZauber55={render};
})();
