// Commit 54: persönliche Kampfrunden-, Initiative- und Effektzeitverwaltung
(() => {
  "use strict";
  const KEY="pf-zeit-kampagnen-v54";
  const page=document.getElementById("zeit"), btn=document.getElementById("btnZeit");
  if(!page||!btn) return;
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||"{}")||{}}catch{return {}}};
  const write=v=>localStorage.setItem(KEY,JSON.stringify(v));
  const campaign=()=>typeof aktiveKampagne==="function"?aktiveKampagne():"Standard";
  const chars=()=>Array.isArray(charaktere)?charaktere.filter(c=>(c.kampagne||"Standard")===campaign()):[];
  const blank=()=>({runde:0,initiative:[],timers:{},freie:[],seq:0});
  function state(){const all=read(), k=campaign();return {...blank(),...(all[k]||{})};}
  function save(st){const all=read();all[campaign()]=st;write(all)}
  const uid=()=>"z"+Date.now().toString(36)+Math.random().toString(36).slice(2,7);
  const esc=s=>String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
  function eligible(effect){const d=String(effect?.dauer||"").trim();return d==="1 Runde/Stufe"||d==="1 Min./Stufe"||d==="10 Runden/Stufe"||d==="Nach Angabe SL"}
  function activeEffects(){const out=[];for(const ch of chars()){const stat=typeof ladeStatusFuerCharakter==="function"?ladeStatusFuerCharakter(ch.id):{};for(const e of (Array.isArray(effekte)?effekte:[])){if(stat?.[e.name]&&eligible(e))out.push({ch,e,key:ch.id+"::"+(e.id||e.name)})}}return out}
  function fillChars(){const a=document.getElementById("zeitTeilnehmerCharakter"),b=document.getElementById("zeitFreierZiel");for(const sel of [a,b]){const first=sel.options[0];sel.innerHTML="";sel.append(first);for(const c of chars()){const o=document.createElement("option");o.value=c.id;o.textContent=c.name||"Unbenannt";sel.append(o)}}}
  function render(){const st=state();document.getElementById("zeitRunde").textContent=st.runde;fillChars();renderInit(st);renderEffects(st);renderFree(st)}
  function renderInit(st){const el=document.getElementById("zeitInitiativeListe");el.innerHTML="";const list=[...st.initiative].filter(x=>Number.isFinite(Number(x.rang))).sort((a,b)=>Number(b.rang)-Number(a.rang)||Number(a.order)-Number(b.order));if(!list.length){el.innerHTML='<p class="zeit-leer-54">Noch keine Teilnehmer.</p>';return}list.forEach((x,i)=>{const same=list.filter(y=>Number(y.rang)===Number(x.rang));const pos=same.findIndex(y=>y.id===x.id);const row=document.createElement("div");row.className="zeit-init-54";row.innerHTML=`<input type="number" min="0" max="40" value="${x.rang}" aria-label="Initiativrang"><span>${esc(x.name)}</span><span class="zeit-init-actions-54"><button type="button" data-up ${pos===0?"disabled":""}>↑</button><button type="button" data-down ${pos===same.length-1?"disabled":""}>↓</button><button type="button" data-del>🗑</button></span>`;row.querySelector("input").onchange=e=>{x.rang=Math.max(0,Math.min(40,Number(e.target.value)||0));save(st);render()};const swap=dir=>{const group=[...st.initiative].filter(y=>Number(y.rang)===Number(x.rang)).sort((a,b)=>a.order-b.order),p=group.findIndex(y=>y.id===x.id),q=p+dir;if(q<0||q>=group.length)return;[group[p].order,group[q].order]=[group[q].order,group[p].order];save(st);render()};row.querySelector("[data-up]").onclick=()=>swap(-1);row.querySelector("[data-down]").onclick=()=>swap(1);row.querySelector("[data-del]").onclick=()=>{st.initiative=st.initiative.filter(y=>y.id!==x.id);save(st);render()};el.append(row)})}
  function statusText(start,dauer,runde){const end=start+dauer-1;if(runde<start)return `Start Runde ${start} · beginnt in ${start-runde} Runde(n) · Ende Runde ${end}`;const rest=Math.max(0,end-runde+1);return rest>0?`Runde ${start} → ${end} · noch ${rest} Runde(n)`:`Runde ${start} → ${end} · ABGELAUFEN`}
  function renderEffects(st){const el=document.getElementById("zeitEffektListe");el.innerHTML="";const list=activeEffects();if(!list.length){el.innerHTML='<p class="zeit-leer-54">Keine geeigneten aktiven Effekte in der aktiven Kampagne.</p>';return}for(const x of list){const t=st.timers[x.key], row=document.createElement("div");const expired=!!t&&st.runde>t.start+t.dauer-1;row.className="zeit-effekt-54"+(expired?" zeit-effekt-abgelaufen-54":"");row.innerHTML=`<strong>${esc(x.e.name)} · ${esc(x.ch.name)}</strong>`;if(t){const p=document.createElement("div");p.className="zeit-rest-54"+(expired?" zeit-abgelaufen-54":"");p.textContent=statusText(t.start,t.dauer,st.runde);const rem=document.createElement("button");rem.type="button";rem.textContent="Timer entfernen";rem.onclick=()=>{delete st.timers[x.key];save(st);render();aktualisiereEffektTimerBanner()};row.append(p,rem)}else{const controls=document.createElement("div");controls.className="zeit-start-54";controls.innerHTML='<span class="zeit-dauer-label-54">Dauer:</span><input class="zeit-dauer-wert-54" type="number" min="1" max="9999" step="1" placeholder="1"><select class="zeit-dauer-art-54" aria-label="Einheit der Effektdauer"><option value="runden">Runden</option><option value="minuten">Minuten</option></select><button type="button">Jetzt starten</button><span>oder Start in Runde</span><input class="zeit-start-runde-54" type="number" min="0" max="9999"><button type="button">Starten</button>';const bs=controls.querySelectorAll("button"),art=controls.querySelector(".zeit-dauer-art-54"),wert=controls.querySelector(".zeit-dauer-wert-54"),startInp=controls.querySelector(".zeit-start-runde-54");const dauer=()=>{const v=Math.max(0,Number(wert.value)||0);return art.value==="minuten"?v*10:v};bs[0].onclick=()=>{const d=dauer();if(d<1){wert.focus();return}st.timers[x.key]={start:st.runde,dauer:d};save(st);render();aktualisiereEffektTimerBanner()};bs[1].onclick=()=>{const d=dauer();if(d<1){wert.focus();return}if(startInp.value===""){startInp.focus();return}st.timers[x.key]={start:Math.max(0,Number(startInp.value)||0),dauer:d};save(st);render();aktualisiereEffektTimerBanner()};row.append(controls)}el.append(row)}}
  function renderFree(st){const el=document.getElementById("zeitFreieEffekte");el.innerHTML="";if(!st.freie.length){el.innerHTML='<p class="zeit-leer-54">Keine freien Effekte.</p>';return}for(const x of st.freie){const row=document.createElement("div");row.className="zeit-effekt-54";row.innerHTML=`<strong>${esc(x.name)}${x.ziel?" · "+esc(x.ziel):""}</strong><div class="zeit-rest-54">${esc(statusText(x.start,x.dauer,st.runde))}</div><button type="button">🗑 Löschen</button>`;row.querySelector("button").onclick=()=>{st.freie=st.freie.filter(y=>y.id!==x.id);save(st);render()};el.append(row)}}
  document.getElementById("btnZeitVorherigeRunde").onclick=()=>{const st=state();st.runde=Math.max(0,st.runde-1);save(st);render();aktualisiereEffektTimerBanner()};
  document.getElementById("btnZeitNaechsteRunde").onclick=()=>{const st=state();st.runde++;save(st);render();aktualisiereEffektTimerBanner()};
  document.getElementById("btnZeitReset").onclick=()=>{if(!confirm("Kampf beendet? Runde, Initiative, freie Effekte und gestartete Timer werden gelöscht. Aktive Charaktereffekte bleiben erhalten."))return;save(blank());render();aktualisiereEffektTimerBanner()};
  document.getElementById("btnZeitTeilnehmer").onclick=()=>{const st=state(),sel=document.getElementById("zeitTeilnehmerCharakter"),free=document.getElementById("zeitTeilnehmerName"),rank=document.getElementById("zeitTeilnehmerRang");const ch=chars().find(c=>c.id===sel.value),name=(ch?.name||free.value||"").trim();if(!name||rank.value==="")return;st.seq=(st.seq||0)+1;st.initiative.push({id:uid(),name,rang:Math.max(0,Math.min(40,Number(rank.value)||0)),order:st.seq});save(st);free.value="";rank.value="";render()};
  document.getElementById("btnZeitFreierEffekt").onclick=()=>{const st=state(),n=document.getElementById("zeitFreierName"),sel=document.getElementById("zeitFreierZiel"),zt=document.getElementById("zeitFreierZielText"),d=document.getElementById("zeitFreierDauer"),sr=document.getElementById("zeitFreierStart");const name=n.value.trim(),dauer=Math.max(1,Number(d.value)||0);if(!name||!dauer)return;const ch=chars().find(c=>c.id===sel.value);st.freie.push({id:uid(),name,ziel:(ch?.name||zt.value||"").trim(),dauer,start:sr.value===""?st.runde:Math.max(0,Number(sr.value)||0)});save(st);n.value=zt.value=d.value=sr.value="";render()};
  function timerInfoFuerEffekt(charId,effekt){const st=state(),key=charId+"::"+(effekt.id||effekt.name),t=st.timers[key];if(!t)return null;const end=t.start+t.dauer-1;if(st.runde<t.start)return {text:`Beginnt in ${t.start-st.runde} Runde(n)`,expired:false};const rest=Math.max(0,end-st.runde+1);return rest>0?{text:`Dauer noch ${rest} Runde(n)`,expired:false}:{text:"Abgelaufen",expired:true};}
  function aktualisiereEffektTimerBanner(){const ch=typeof aktiverCharakter==="function"?aktiverCharakter():null;if(!ch)return;document.querySelectorAll("#boniListe .effekt").forEach(karte=>{karte.querySelectorAll(".effekt-zeitstatus-54").forEach(el=>el.remove());const name=karte.querySelector(".effekt-name")?.textContent||"",e=(Array.isArray(effekte)?effekte:[]).find(x=>x.name===name);if(!e||!eligible(e))return;const info=timerInfoFuerEffekt(ch.id,e);if(!info)return;const ziel=karte.querySelector(".effekt-info");if(!ziel)return;const el=document.createElement("div");el.className="effekt-zeitstatus-54"+(info.expired?" effekt-zeitstatus-abgelaufen-54":"");el.textContent=info.text;ziel.appendChild(el);});}
  const alteBaueEffektliste54=typeof baueEffektliste==="function"?baueEffektliste:null;if(alteBaueEffektliste54){baueEffektliste=function(){alteBaueEffektliste54();aktualisiereEffektTimerBanner();};}
  const oldShow=zeigeSeite;
  zeigeSeite=function(name){
    oldShow(name);
    if(name==="zeit") render();
  };
  btn.onclick=()=>zeigeSeite("zeit");
  document.getElementById("btnDashboard")?.remove();
  const nav=document.querySelector("nav"), admin=document.getElementById("btnAdmin");if(nav&&admin)nav.insertBefore(btn,document.getElementById("btnVermoegen"));
  if(typeof initialisiereCommit21==="undefined"){} // Marker für Commit 54
})();
